###
# group: actividad
# @name actividad
GET {{host}}/api/actividad
Accept: application/json
Content-Type: application/x-www-form-urlencoded
Authorization: Bearer {{$auth.token("MypasswordConfig")}}

###
# group: actividad
# @name getActividad
GET {{host}}/api/actividad/8?XDEBUG_SESSION_START=PHPSTORM
Accept: application/json
Content-Type: application/x-www-form-urlencoded
Authorization: Bearer {{$auth.token("MypasswordConfig")}}

###
# @group: actividad
# @name createActividad
POST {{host}}/api/actividad?XDEBUG_SESSION_START=PHPSTORM
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{$auth.token("MypasswordConfig")}}
XDEBUG_SESSION: PHPSTORM;
XDEBUG_SESSION_START: PHPSTORM;

{
    "nombre": "escalada4",
    "foto": "http://localhost/assets/img/logo.png",
    "descripcion": "escalada escalada escalada escalada escalada escaladaescalada",
    "fecha": "2024-04-22 19:46:09",
    "filterBy": "",
    "filter": "",
    "orderBy": "",
    "order": "",
    "page": "",
    "perPage": ""
}

###
# @group: actividad
# @name updateActividad
PUT {{host}}/api/actividad/10?XDEBUG_SESSION_START=PHPSTORM
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{$auth.token("MypasswordConfig")}}
XDEBUG_SESSION: PHPSTORM;
XDEBUG_SESSION_START: PHPSTORM;

{
    "nombre": "escalada actualizada",
    "foto": "http://localhost/assets/img/logo.png",
    "descripcion": "escalada escalada escalada escalada escalada escaladaescalada",
    "fecha": "2024-04-22 19:46:09",
    "filterBy": "",
    "filter": "",
    "orderBy": "",
    "order": "",
    "page": "",
    "perPage": ""
}

###
# @group: actividad
# @name deleteActividad
DELETE {{host}}/api/actividad/90?XDEBUG_SESSION_START=PHPSTORM
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{$auth.token("MypasswordConfig")}}
